name: Quizmaster-build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - 'docker-compose.yml'
      - 'quizboard'
      - 'docs'

jobs:
  set_version:
    name: set image name
    runs-on: ubuntu-latest
    steps:
      - name: create docker tag
        run: echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    outputs:
      image: ghcr.io/${{ github.repository }}/leesah-quizmaster:${{ env.TAG }}


  build:
    name: build docker image
    runs-on: ubuntu-latest
    needs: set_version
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - name: test and build
        run: ../gradlew build
        working-directory: quizmaster
      - name: build docker image
        run: docker build . --pull -t ${{ needs.set_version.outputs.image }}
        working-directory: quizmaster
      - name: push docker image
        run: |
          docker login --username "$GITHUB_REPOSITORY" -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker push ${{ needs.set_version.outputs.image }}

  deployDev:
    name: Deploy to dev
    needs: [ set_version, build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/quizmaster-dev.yml
          IMAGE: ${{ needs.set_version.outputs.image }}
